version: '3.9'

services:
  app:
    build: .
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://root:Root1234_@localhost:3001/OTP
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Root1234_
      MYSQL_DATABASE: OTP
      MYSQL_USER: otp_user
      MYSQL_PASSWORD: Root1234_
    ports:
      - "3001:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
